// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: petstore/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReponseCode int32

const (
	ReponseCode_ResponseCode_UNDEFINED     ReponseCode = 0
	ReponseCode_ResponseCode_SUCCESSFUL    ReponseCode = 200
	ReponseCode_ResponseCode_INVALID_VALUE ReponseCode = 400
	ReponseCode_ResponseCode_NOT_FOUND     ReponseCode = 404
	ReponseCode_ResponseCode_INVALID_INPUT ReponseCode = 405
)

// Enum value maps for ReponseCode.
var (
	ReponseCode_name = map[int32]string{
		0:   "ResponseCode_UNDEFINED",
		200: "ResponseCode_SUCCESSFUL",
		400: "ResponseCode_INVALID_VALUE",
		404: "ResponseCode_NOT_FOUND",
		405: "ResponseCode_INVALID_INPUT",
	}
	ReponseCode_value = map[string]int32{
		"ResponseCode_UNDEFINED":     0,
		"ResponseCode_SUCCESSFUL":    200,
		"ResponseCode_INVALID_VALUE": 400,
		"ResponseCode_NOT_FOUND":     404,
		"ResponseCode_INVALID_INPUT": 405,
	}
)

func (x ReponseCode) Enum() *ReponseCode {
	p := new(ReponseCode)
	*p = x
	return p
}

func (x ReponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_petstore_v1_common_proto_enumTypes[0].Descriptor()
}

func (ReponseCode) Type() protoreflect.EnumType {
	return &file_petstore_v1_common_proto_enumTypes[0]
}

func (x ReponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReponseCode.Descriptor instead.
func (ReponseCode) EnumDescriptor() ([]byte, []int) {
	return file_petstore_v1_common_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    ReponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=petstore.v1.ReponseCode" json:"code,omitempty"`
	Type    string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Message string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_petstore_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_petstore_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_petstore_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() ReponseCode {
	if x != nil {
		return x.Code
	}
	return ReponseCode_ResponseCode_UNDEFINED
}

func (x *Response) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_petstore_v1_common_proto protoreflect.FileDescriptor

var file_petstore_v1_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x65, 0x74, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x66, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0xa6, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x5f,
	0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x17, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x46, 0x55, 0x4c, 0x10, 0xc8, 0x01, 0x12, 0x1f, 0x0a, 0x1a, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x90, 0x03, 0x12, 0x1b, 0x0a, 0x16, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46,
	0x4f, 0x55, 0x4e, 0x44, 0x10, 0x94, 0x03, 0x12, 0x1f, 0x0a, 0x1a, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x95, 0x03, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x79, 0x6e, 0x65, 0x61, 0x72, 0x6d, 0x65,
	0x2f, 0x70, 0x65, 0x74, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_petstore_v1_common_proto_rawDescOnce sync.Once
	file_petstore_v1_common_proto_rawDescData = file_petstore_v1_common_proto_rawDesc
)

func file_petstore_v1_common_proto_rawDescGZIP() []byte {
	file_petstore_v1_common_proto_rawDescOnce.Do(func() {
		file_petstore_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_petstore_v1_common_proto_rawDescData)
	})
	return file_petstore_v1_common_proto_rawDescData
}

var file_petstore_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_petstore_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_petstore_v1_common_proto_goTypes = []interface{}{
	(ReponseCode)(0), // 0: petstore.v1.ReponseCode
	(*Response)(nil), // 1: petstore.v1.Response
}
var file_petstore_v1_common_proto_depIdxs = []int32{
	0, // 0: petstore.v1.Response.code:type_name -> petstore.v1.ReponseCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_petstore_v1_common_proto_init() }
func file_petstore_v1_common_proto_init() {
	if File_petstore_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_petstore_v1_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_petstore_v1_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_petstore_v1_common_proto_goTypes,
		DependencyIndexes: file_petstore_v1_common_proto_depIdxs,
		EnumInfos:         file_petstore_v1_common_proto_enumTypes,
		MessageInfos:      file_petstore_v1_common_proto_msgTypes,
	}.Build()
	File_petstore_v1_common_proto = out.File
	file_petstore_v1_common_proto_rawDesc = nil
	file_petstore_v1_common_proto_goTypes = nil
	file_petstore_v1_common_proto_depIdxs = nil
}
